//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Controls.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Controls.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Add Column.
        /// </summary>
        public static string AddColumn_s {
            get {
                return ResourceManager.GetString("AddColumn_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Tab.
        /// </summary>
        public static string AddTab_s {
            get {
                return ResourceManager.GetString("AddTab_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear selected value.
        /// </summary>
        public static string ClearSelectedValue_s {
            get {
                return ResourceManager.GetString("ClearSelectedValue_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal.
        /// </summary>
        public static string Horizontal_s {
            get {
                return ResourceManager.GetString("Horizontal_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NESW.
        /// </summary>
        public static string NESW_s {
            get {
                return ResourceManager.GetString("NESW_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NWSE.
        /// </summary>
        public static string NWSE_s {
            get {
                return ResourceManager.GetString("NWSE_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Remove Column.
        /// </summary>
        public static string RemoveColumn_s {
            get {
                return ResourceManager.GetString("RemoveColumn_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Tab.
        /// </summary>
        public static string RemoveTab_s {
            get {
                return ResourceManager.GetString("RemoveTab_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Select attached controls.
        /// </summary>
        public static string SelectAttachedControls_s {
            get {
                return ResourceManager.GetString("SelectAttachedControls_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Subform16x16 {
            get {
                object obj = ResourceManager.GetObject("Subform16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to .
        /// </summary>
        public static string SwitchTo_s {
            get {
                return ResourceManager.GetString("SwitchTo_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TableControl {
            get {
                object obj = ResourceManager.GetObject("TableControl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TabPage.
        /// </summary>
        public static string TabPage_s {
            get {
                return ResourceManager.GetString("TabPage_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical.
        /// </summary>
        public static string Vertical_s {
            get {
                return ResourceManager.GetString("Vertical_s", resourceCulture);
            }
        }
    }
}
