using System;
using System.Runtime.InteropServices;

namespace com.magicsoftware.richclient
{
   // IObjectWithSite is not our custom interface by it defined in COM so ComImport attribute
   // is set and it will not appear in type library generated by RegAsm.
   // this interface was originally declared in ocidl.h (COM platform) insted of importing all intrfaces in the file using tlb
   // we have declared it localy for our use
   //we need this interface in order to Communicate with the site/conatiner 
   [ComImport, Guid("FC4801A3-2BA9-11CF-A229-00AA003D7352"),
   InterfaceType(ComInterfaceType.InterfaceIsIUnknown)] //tell ust that this interface inherits fron IUnKonown
   public interface IObjectWithSite
   {
      [DispId(1)]
      void SetSite([In, MarshalAs(UnmanagedType.IUnknown)] object pUnkSite);

      [DispId(2)]
      void GetSite([In] ref Guid riid, [Out] IntPtr ppvSite);
   }
}